// <auto-generated />
using System;
using Dragonmind.Knowledge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Dragonmind.Knowledge.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    [Migration("20260915224553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("knowledge")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dragonmind.Knowledge.Domain.Aggregates.KnowledgeDocumentAggregate.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ScopeId")
                        .HasDatabaseName("ix_documents_scope_id");

                    b.ToTable("documents", "knowledge");
                });

            modelBuilder.Entity("Dragonmind.Knowledge.Domain.Aggregates.KnowledgeDocumentAggregate.KnowledgeDocument", b =>
                {
                    b.OwnsOne("Dragonmind.Knowledge.Domain.ValueObjects.DocumentContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("KnowledgeDocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .HasColumnType("text")
                                .HasColumnName("category");

                            b1.Property<string>("Source")
                                .HasColumnType("text")
                                .HasColumnName("source");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("content");

                            b1.HasKey("KnowledgeDocumentId");

                            b1.ToTable("documents", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("KnowledgeDocumentId")
                                .HasConstraintName("fk_documents_documents_id");
                        });

                    b.OwnsOne("Dragonmind.Knowledge.Domain.ValueObjects.Embedding", "Embedding", b1 =>
                        {
                            b1.Property<Guid>("KnowledgeDocumentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Vector>("Vector")
                                .IsRequired()
                                .HasColumnType("vector(1536)")
                                .HasColumnName("vector");

                            b1.HasKey("KnowledgeDocumentId");

                            b1.ToTable("documents", "knowledge");

                            b1.WithOwner()
                                .HasForeignKey("KnowledgeDocumentId")
                                .HasConstraintName("fk_documents_documents_id");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
